// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FruitboxController from "./fruitbox_controller"
application.register("fruitbox", FruitboxController)

import MultiplayerFruitboxController from "./multiplayer_fruitbox_controller"
application.register("multiplayer-fruitbox", MultiplayerFruitboxController)
